// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG4Joqq7DCk9NDIuF8nOj5yzcXv9ndUlc',
    appId: '1:514347165690:web:ee20a384b993c0cbc5e643',
    messagingSenderId: '514347165690',
    projectId: 'rental-mobil-389304',
    authDomain: 'rental-mobil-389304.firebaseapp.com',
    storageBucket: 'rental-mobil-389304.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTfmea_wckProMVivuKoXVRRoKE9ArwEs',
    appId: '1:514347165690:android:d22928759c6e83eec5e643',
    messagingSenderId: '514347165690',
    projectId: 'rental-mobil-389304',
    storageBucket: 'rental-mobil-389304.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHT6FFnfFADsvHmgoAVqC16i6JTtU-HTI',
    appId: '1:514347165690:ios:b2b84eeab77e97ebc5e643',
    messagingSenderId: '514347165690',
    projectId: 'rental-mobil-389304',
    storageBucket: 'rental-mobil-389304.appspot.com',
    iosClientId: '514347165690-dgk569mla1qo0spc022g1un4998iser6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gorentcar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHT6FFnfFADsvHmgoAVqC16i6JTtU-HTI',
    appId: '1:514347165690:ios:521e6790e52c85adc5e643',
    messagingSenderId: '514347165690',
    projectId: 'rental-mobil-389304',
    storageBucket: 'rental-mobil-389304.appspot.com',
    iosClientId: '514347165690-ls8v2dublq5shgjqhglfb985nck7867v.apps.googleusercontent.com',
    iosBundleId: 'com.example.gorentcar.RunnerTests',
  );
}
